# =============================================================================
# Zone Configuration
# =============================================================================

variable "zone_name" {
  description = "Name of the network zone (e.g., 'incus.accuser.dev'). Becomes the DNS zone name."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9.-]*[a-z0-9]$", var.zone_name))
    error_message = "Zone name must be a valid DNS domain (lowercase, alphanumeric with dots and hyphens)"
  }
}

variable "description" {
  description = "Human-readable description of the zone"
  type        = string
  default     = "Incus container DNS zone"
}

variable "default_ttl" {
  description = "Default TTL for zone records in seconds"
  type        = number
  default     = 300

  validation {
    condition     = var.default_ttl >= 60 && var.default_ttl <= 86400
    error_message = "TTL must be between 60 and 86400 seconds"
  }
}

# =============================================================================
# Peer Configuration (for cross-environment zones)
# =============================================================================

variable "peers" {
  description = "Map of peer Incus servers to include records from. Key is peer name, value is peer configuration."
  type = map(object({
    address = string
  }))
  default = {}
}

# =============================================================================
# Zone Transfer Peers (DNS servers allowed to pull the zone via AXFR)
# =============================================================================

variable "transfer_peers" {
  description = "Map of DNS servers allowed to request zone transfers. Key is peer name, value is the source IP address the Incus host will see. For OVN, use the network's NAT IP (from volatile.network.ipv4.address)."
  type        = map(string)
  default     = {}
}

# =============================================================================
# DNS Server Configuration
# =============================================================================

variable "configure_dns_server" {
  description = "Configure core.dns_address on Incus server to enable DNS serving. Set to false if already configured or managed elsewhere."
  type        = bool
  default     = true
}

variable "dns_listen_address" {
  description = "Address for Incus DNS server to listen on. Use ':5353' to bind all interfaces, or a specific host IP like '192.168.68.84:5353'. Note: This must be an IP the host actually has (not an OVN virtual gateway). Use non-standard port to avoid conflicts with CoreDNS on port 53."
  type        = string
  default     = ":5353"
}

variable "dns_reachable_address" {
  description = "Address where CoreDNS can reach the Incus DNS server for zone transfers. For OVN environments, this should be the host's LAN IP (e.g., '192.168.68.84:5353'). If empty, defaults to dns_listen_address."
  type        = string
  default     = ""
}

# =============================================================================
# Custom Records
# =============================================================================

variable "custom_records" {
  description = "Additional custom zone records not automatically generated by Incus"
  type = list(object({
    name        = string
    description = optional(string, "")
    entries = list(object({
      type  = string # A, AAAA, CNAME, TXT, SRV, etc.
      value = string
      ttl   = optional(number)
    }))
  }))
  default = []
}
