# Bootstrap Terraform Project
# This project sets up the prerequisites for the main infrastructure:
# - Incus storage buckets configuration
# - Storage pool for Terraform state
# - Storage bucket for Terraform state
# - S3 access credentials

# Configure Incus storage buckets address
resource "null_resource" "configure_storage_buckets" {
  provisioner "local-exec" {
    command = <<-EOT
      # Check if already configured
      CURRENT_ADDR=$(incus config get core.storage_buckets_address 2>/dev/null || echo "")

      if [ -z "$CURRENT_ADDR" ]; then
        echo "Configuring Incus storage buckets address..."
        incus config set core.storage_buckets_address ${var.storage_buckets_address}
        echo "Storage buckets address set to: ${var.storage_buckets_address}"
      else
        echo "Storage buckets address already configured: $CURRENT_ADDR"
      fi
    EOT
  }
}

# Create storage pool for Terraform state (if it doesn't exist)
resource "null_resource" "create_storage_pool" {
  depends_on = [null_resource.configure_storage_buckets]

  provisioner "local-exec" {
    command = <<-EOT
      # Check if pool exists
      if incus storage list --format csv | grep -q "^${var.storage_pool_name},"; then
        echo "Storage pool '${var.storage_pool_name}' already exists"
      else
        echo "Creating storage pool '${var.storage_pool_name}'..."
        incus storage create ${var.storage_pool_name} ${var.storage_pool_driver}
        echo "Storage pool created successfully"
      fi
    EOT
  }
}

# Create storage bucket for Terraform state
resource "null_resource" "create_storage_bucket" {
  depends_on = [null_resource.create_storage_pool]

  provisioner "local-exec" {
    command = <<-EOT
      # Check if bucket exists
      if incus storage bucket list ${var.storage_pool_name} --format csv | grep -q "^${var.bucket_name},"; then
        echo "Storage bucket '${var.bucket_name}' already exists"
      else
        echo "Creating storage bucket '${var.bucket_name}'..."
        incus storage bucket create ${var.storage_pool_name} ${var.bucket_name}
        echo "Storage bucket created successfully"
      fi
    EOT
  }
}

# Generate S3 credentials for the bucket
resource "null_resource" "generate_credentials" {
  depends_on = [null_resource.create_storage_bucket]

  provisioner "local-exec" {
    command = <<-EOT
      # Check if credentials already exist
      if incus storage bucket key list ${var.storage_pool_name} ${var.bucket_name} --format csv | grep -q "^${var.bucket_key_name},"; then
        echo "Credentials '${var.bucket_key_name}' already exist"
        echo "To regenerate, delete the key first:"
        echo "  incus storage bucket key delete ${var.storage_pool_name} ${var.bucket_name} ${var.bucket_key_name}"
      else
        echo "Generating S3 credentials..."
        incus storage bucket key create ${var.storage_pool_name} ${var.bucket_name} ${var.bucket_key_name} > ${var.credentials_output_file}
        echo ""
        echo "Credentials saved to: ${var.credentials_output_file}"
        echo ""
        echo "IMPORTANT: Save these credentials securely!"
        echo "You will need them to configure the Terraform backend."
        echo ""
        cat ${var.credentials_output_file}
      fi
    EOT
  }
}

# Create backend.hcl file for main Terraform project
resource "null_resource" "create_backend_config" {
  depends_on = [null_resource.generate_credentials]

  provisioner "local-exec" {
    command = <<-EOT
      if [ -f "${var.credentials_output_file}" ]; then
        # Extract credentials from output file
        ACCESS_KEY=$(grep "Access key:" ${var.credentials_output_file} | awk '{print $3}')
        SECRET_KEY=$(grep "Secret key:" ${var.credentials_output_file} | awk '{print $3}')

        # Create backend.hcl in the main terraform directory
        cat > ${var.backend_config_output} <<-EOF
# Terraform S3 Backend Configuration
# Auto-generated by bootstrap process
# DO NOT COMMIT THIS FILE - IT CONTAINS SECRETS

bucket     = "${var.bucket_name}"
endpoint   = "${var.storage_buckets_endpoint}"
access_key = "$ACCESS_KEY"
secret_key = "$SECRET_KEY"
EOF

        echo ""
        echo "Backend configuration created: ${var.backend_config_output}"
        echo ""
        echo "Next steps:"
        echo "1. cd ../  # Return to main terraform directory"
        echo "2. terraform init -backend-config=backend.hcl"
        echo "3. terraform plan"
        echo "4. terraform apply"
      else
        echo "Credentials file not found. Using existing credentials."
      fi
    EOT
  }
}
