#!/bin/sh
# TLS-aware entrypoint for Mosquitto MQTT broker
# Requests certificate from step-ca and configures TLS if enabled
set -e

TLS_DIR="/mosquitto/tls"
CERT_FILE="${TLS_DIR}/mosquitto.crt"
KEY_FILE="${TLS_DIR}/mosquitto.key"
CA_FILE="${TLS_DIR}/ca.crt"
CONFIG_FILE="/mosquitto/config/mosquitto.conf"

# Default port settings (can be overridden via environment variables)
MQTT_PORT="${MQTT_PORT:-1883}"
MQTTS_PORT="${MQTTS_PORT:-8883}"

# Function to request certificate from step-ca
request_certificate() {
    echo "Requesting certificate from step-ca..."

    # Bootstrap trust to the CA
    step ca bootstrap --ca-url "${STEPCA_URL}" --fingerprint "${STEPCA_FINGERPRINT}" --force

    # Get hostname for certificate
    HOSTNAME=$(hostname)

    # Request certificate using ACME
    step ca certificate "${HOSTNAME}" "${CERT_FILE}" "${KEY_FILE}" \
        --ca-url "${STEPCA_URL}" \
        --provisioner acme \
        --not-after "${CERT_DURATION}" \
        --force

    # Copy root CA for client verification
    cp "$(step path)/certs/root_ca.crt" "${CA_FILE}"

    # Fix permissions for mosquitto user
    chown mosquitto:mosquitto "${CERT_FILE}" "${KEY_FILE}" "${CA_FILE}"
    chmod 640 "${CERT_FILE}" "${KEY_FILE}" "${CA_FILE}"

    echo "Certificate obtained successfully"
}

# Function to generate Mosquitto configuration
generate_config() {
    echo "Generating Mosquitto configuration..."

    # Start with base config
    cat > "${CONFIG_FILE}" <<EOF
# Mosquitto MQTT Broker Configuration
# Generated by entrypoint-tls.sh

# Persistence
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true

# Security defaults
allow_anonymous false
EOF

    # Check if password file exists and configure authentication
    if [ -f "/mosquitto/config/passwd" ]; then
        echo "password_file /mosquitto/config/passwd" >> "${CONFIG_FILE}"
        echo "Configured password file authentication"
    else
        # Allow anonymous if no password file (for initial setup/testing)
        sed -i 's/allow_anonymous false/allow_anonymous true/' "${CONFIG_FILE}"
        echo "WARNING: No password file found, allowing anonymous connections"
    fi

    # Add listener configuration based on TLS mode
    if [ "${ENABLE_TLS}" = "true" ]; then
        cat >> "${CONFIG_FILE}" <<EOF

# Plain MQTT listener (for internal use)
listener ${MQTT_PORT} 0.0.0.0
protocol mqtt

# TLS MQTT listener
listener ${MQTTS_PORT} 0.0.0.0
protocol mqtt
certfile ${CERT_FILE}
keyfile ${KEY_FILE}
cafile ${CA_FILE}
tls_version tlsv1.2
EOF
        echo "Configured TLS listener on port ${MQTTS_PORT}"
    else
        cat >> "${CONFIG_FILE}" <<EOF

# Plain MQTT listener
listener ${MQTT_PORT} 0.0.0.0
protocol mqtt
EOF
    fi

    echo "Configuration generated at ${CONFIG_FILE}"
}

# Main logic
if [ "${ENABLE_TLS}" = "true" ]; then
    echo "TLS mode enabled"

    # Validate required environment variables
    if [ -z "${STEPCA_URL}" ]; then
        echo "ERROR: STEPCA_URL is required when ENABLE_TLS=true"
        exit 1
    fi

    if [ -z "${STEPCA_FINGERPRINT}" ]; then
        echo "ERROR: STEPCA_FINGERPRINT is required when ENABLE_TLS=true"
        exit 1
    fi

    # Request certificate
    request_certificate
fi

# Generate configuration
generate_config

# Start Mosquitto
echo "Starting Mosquitto MQTT broker..."
exec /usr/sbin/mosquitto -c "${CONFIG_FILE}" "$@"
