#!/bin/sh
# TLS-aware entrypoint for Mosquitto MQTT broker
# Requests certificate from step-ca and configures TLS if enabled
set -eu

# =============================================================================
# Logging Functions
# =============================================================================
log_info()  { echo "INFO:  $*"; }
log_warn()  { echo "WARN:  $*" >&2; }
log_error() { echo "ERROR: $*" >&2; }

# =============================================================================
# Configuration
# =============================================================================
TLS_DIR="/mosquitto/tls"
CERT_FILE="${TLS_DIR}/mosquitto.crt"
KEY_FILE="${TLS_DIR}/mosquitto.key"
CA_FILE="${TLS_DIR}/ca.crt"
CONFIG_FILE="/mosquitto/config/mosquitto.conf"

# Default port settings (can be overridden via environment variables)
MQTT_PORT="${MQTT_PORT:-1883}"
MQTTS_PORT="${MQTTS_PORT:-8883}"

# =============================================================================
# Functions
# =============================================================================

# Request certificate from step-ca
request_certificate() {
    log_info "Requesting certificate from step-ca..."

    # Bootstrap trust to the CA
    if ! step ca bootstrap --ca-url "${STEPCA_URL}" --fingerprint "${STEPCA_FINGERPRINT}" --force; then
        log_error "Failed to bootstrap CA trust"
        return 1
    fi

    # Get hostname for certificate
    HOSTNAME=$(hostname)
    log_info "Requesting certificate for hostname: ${HOSTNAME}"

    # Request certificate using ACME
    if ! step ca certificate "${HOSTNAME}" "${CERT_FILE}" "${KEY_FILE}" \
        --ca-url "${STEPCA_URL}" \
        --provisioner acme \
        --not-after "${CERT_DURATION:-24h}" \
        --force; then
        log_error "Failed to obtain certificate"
        return 1
    fi

    # Copy root CA for client verification
    if ! cp "$(step path)/certs/root_ca.crt" "${CA_FILE}"; then
        log_error "Failed to copy root CA certificate"
        return 1
    fi

    # Fix permissions for mosquitto user
    if ! chown mosquitto:mosquitto "${CERT_FILE}" "${KEY_FILE}" "${CA_FILE}"; then
        log_error "Failed to set certificate ownership"
        return 1
    fi

    if ! chmod 640 "${CERT_FILE}" "${KEY_FILE}" "${CA_FILE}"; then
        log_error "Failed to set certificate permissions"
        return 1
    fi

    log_info "Certificate obtained successfully"
}

# Generate Mosquitto configuration
generate_config() {
    log_info "Generating Mosquitto configuration..."

    # Start with base config
    if ! cat > "${CONFIG_FILE}" <<EOF
# Mosquitto MQTT Broker Configuration
# Generated by entrypoint-tls.sh

# Persistence
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true

# Security defaults
allow_anonymous false
EOF
    then
        log_error "Failed to create base config"
        return 1
    fi

    # Check if password file exists and configure authentication
    if [ -f "/mosquitto/config/passwd" ]; then
        echo "password_file /mosquitto/config/passwd" >> "${CONFIG_FILE}"
        log_info "Configured password file authentication"
    else
        # Allow anonymous if no password file (for initial setup/testing)
        sed -i 's/allow_anonymous false/allow_anonymous true/' "${CONFIG_FILE}"
        log_warn "No password file found, allowing anonymous connections"
    fi

    # Add listener configuration based on TLS mode
    if [ "${ENABLE_TLS:-false}" = "true" ]; then
        cat >> "${CONFIG_FILE}" <<EOF

# Plain MQTT listener (for internal use)
listener ${MQTT_PORT} 0.0.0.0
protocol mqtt

# TLS MQTT listener
listener ${MQTTS_PORT} 0.0.0.0
protocol mqtt
certfile ${CERT_FILE}
keyfile ${KEY_FILE}
cafile ${CA_FILE}
tls_version tlsv1.2
EOF
        log_info "Configured TLS listener on port ${MQTTS_PORT}"
    else
        cat >> "${CONFIG_FILE}" <<EOF

# Plain MQTT listener
listener ${MQTT_PORT} 0.0.0.0
protocol mqtt
EOF
    fi

    log_info "Configuration generated at ${CONFIG_FILE}"
}

# Validate required TLS environment variables
validate_tls_config() {
    local valid=true

    if [ -z "${STEPCA_URL:-}" ]; then
        log_error "STEPCA_URL is required when ENABLE_TLS=true"
        valid=false
    fi

    if [ -z "${STEPCA_FINGERPRINT:-}" ]; then
        log_error "STEPCA_FINGERPRINT is required when ENABLE_TLS=true"
        valid=false
    fi

    if [ "${valid}" = "false" ]; then
        return 1
    fi
}

# =============================================================================
# Main
# =============================================================================
main() {
    if [ "${ENABLE_TLS:-false}" = "true" ]; then
        log_info "TLS mode enabled"

        # Validate configuration
        if ! validate_tls_config; then
            log_error "TLS configuration validation failed"
            exit 1
        fi

        # Request certificate
        if ! request_certificate; then
            log_error "Certificate request failed"
            exit 1
        fi
    fi

    # Generate configuration
    if ! generate_config; then
        log_error "Configuration generation failed"
        exit 1
    fi

    # Start Mosquitto
    log_info "Starting Mosquitto MQTT broker..."
    exec /usr/sbin/mosquitto -c "${CONFIG_FILE}" "$@"
}

main "$@"
