#!/bin/sh
# TLS-aware entrypoint for Loki
# Requests certificate from step-ca and configures TLS if enabled
# Also supports retention configuration via environment variables
set -eu

# =============================================================================
# Logging Functions
# =============================================================================
log_info()  { echo "INFO:  $*"; }
log_warn()  { echo "WARN:  $*" >&2; }
log_error() { echo "ERROR: $*" >&2; }

# =============================================================================
# Configuration
# =============================================================================
TLS_DIR="/etc/loki/tls"
CERT_FILE="${TLS_DIR}/loki.crt"
KEY_FILE="${TLS_DIR}/loki.key"
CA_FILE="${TLS_DIR}/ca.crt"
CONFIG_FILE="/etc/loki/loki-config.yaml"
TLS_CONFIG_FILE="/etc/loki/loki-tls-config.yaml"
RUNTIME_CONFIG_FILE="/etc/loki/loki-runtime-config.yaml"

# Default retention settings (can be overridden via environment variables)
RETENTION_PERIOD="${RETENTION_PERIOD:-}"
RETENTION_DELETE_DELAY="${RETENTION_DELETE_DELAY:-2h}"

# =============================================================================
# Functions
# =============================================================================

# Request certificate from step-ca
request_certificate() {
    log_info "Requesting certificate from step-ca..."

    # Bootstrap trust to the CA
    if ! step ca bootstrap --ca-url "${STEPCA_URL}" --fingerprint "${STEPCA_FINGERPRINT}" --force; then
        log_error "Failed to bootstrap CA trust"
        return 1
    fi

    # Get hostname for certificate
    HOSTNAME=$(hostname)
    log_info "Requesting certificate for hostname: ${HOSTNAME}"

    # Request certificate using ACME
    if ! step ca certificate "${HOSTNAME}" "${CERT_FILE}" "${KEY_FILE}" \
        --ca-url "${STEPCA_URL}" \
        --provisioner acme \
        --not-after "${CERT_DURATION:-24h}" \
        --force; then
        log_error "Failed to obtain certificate"
        return 1
    fi

    # Copy root CA for client verification
    if ! cp "$(step path)/certs/root_ca.crt" "${CA_FILE}"; then
        log_error "Failed to copy root CA certificate"
        return 1
    fi

    log_info "Certificate obtained successfully"
}

# Generate retention config section
generate_retention_config() {
    if [ -n "${RETENTION_PERIOD}" ]; then
        log_info "Retention enabled: ${RETENTION_PERIOD}" >&2
        cat <<EOF

# Retention configuration
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 24
  retention_period: ${RETENTION_PERIOD}

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: ${RETENTION_DELETE_DELAY}
  retention_delete_worker_count: 150
  delete_request_store: filesystem
EOF
    else
        log_info "Retention disabled (no RETENTION_PERIOD set)" >&2
        cat <<EOF

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 24
EOF
    fi
}

# Create runtime config (non-TLS)
create_runtime_config() {
    log_info "Creating runtime config..."

    if ! cat > "${RUNTIME_CONFIG_FILE}" <<EOF
# Loki configuration
# Generated by entrypoint-tls.sh

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

$(generate_retention_config)

analytics:
  reporting_enabled: false
EOF
    then
        log_error "Failed to create runtime config"
        return 1
    fi

    log_info "Runtime config created at ${RUNTIME_CONFIG_FILE}"
}

# Create TLS-enabled config
create_tls_config() {
    log_info "Creating TLS config..."

    if ! cat > "${TLS_CONFIG_FILE}" <<EOF
# Loki configuration with TLS
# Generated by entrypoint-tls.sh

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_tls_config:
    cert_file: ${CERT_FILE}
    key_file: ${KEY_FILE}
  grpc_tls_config:
    cert_file: ${CERT_FILE}
    key_file: ${KEY_FILE}

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

$(generate_retention_config)

analytics:
  reporting_enabled: false
EOF
    then
        log_error "Failed to create TLS config"
        return 1
    fi

    log_info "TLS config created at ${TLS_CONFIG_FILE}"
}

# Validate required TLS environment variables
validate_tls_config() {
    local valid=true

    if [ -z "${STEPCA_URL:-}" ]; then
        log_error "STEPCA_URL is required when ENABLE_TLS=true"
        valid=false
    fi

    if [ -z "${STEPCA_FINGERPRINT:-}" ]; then
        log_error "STEPCA_FINGERPRINT is required when ENABLE_TLS=true"
        valid=false
    fi

    if [ "${valid}" = "false" ]; then
        return 1
    fi
}

# =============================================================================
# Main
# =============================================================================
main() {
    if [ "${ENABLE_TLS:-false}" = "true" ]; then
        log_info "TLS mode enabled"

        # Validate configuration
        if ! validate_tls_config; then
            log_error "TLS configuration validation failed"
            exit 1
        fi

        # Request certificate
        if ! request_certificate; then
            log_error "Certificate request failed"
            exit 1
        fi

        # Create TLS config (includes retention if configured)
        if ! create_tls_config; then
            log_error "TLS config creation failed"
            exit 1
        fi

        # Start Loki with TLS config
        log_info "Starting Loki with TLS..."
        exec /usr/bin/loki -config.file="${TLS_CONFIG_FILE}" "$@"

    elif [ -n "${RETENTION_PERIOD}" ]; then
        log_info "TLS mode disabled, retention enabled"

        # Create runtime config with retention
        if ! create_runtime_config; then
            log_error "Runtime config creation failed"
            exit 1
        fi

        # Start Loki with runtime config
        log_info "Starting Loki with retention configuration..."
        exec /usr/bin/loki -config.file="${RUNTIME_CONFIG_FILE}" "$@"

    else
        log_info "TLS mode disabled, starting Loki with default config..."
        exec /usr/bin/loki -config.file="${CONFIG_FILE}" "$@"
    fi
}

main "$@"
