#!/bin/sh
# TLS-aware entrypoint for Loki
# Requests certificate from step-ca and configures TLS if enabled
set -e

TLS_DIR="/etc/loki/tls"
CERT_FILE="${TLS_DIR}/loki.crt"
KEY_FILE="${TLS_DIR}/loki.key"
CA_FILE="${TLS_DIR}/ca.crt"
CONFIG_FILE="/etc/loki/loki-config.yaml"
TLS_CONFIG_FILE="/etc/loki/loki-tls-config.yaml"

# Function to request certificate from step-ca
request_certificate() {
    echo "Requesting certificate from step-ca..."

    # Bootstrap trust to the CA
    step ca bootstrap --ca-url "${STEPCA_URL}" --fingerprint "${STEPCA_FINGERPRINT}" --force

    # Get hostname for certificate
    HOSTNAME=$(hostname)

    # Request certificate using ACME
    step ca certificate "${HOSTNAME}" "${CERT_FILE}" "${KEY_FILE}" \
        --ca-url "${STEPCA_URL}" \
        --provisioner acme \
        --not-after "${CERT_DURATION}" \
        --force

    # Copy root CA for client verification
    cp "$(step path)/certs/root_ca.crt" "${CA_FILE}"

    echo "Certificate obtained successfully"
}

# Function to create TLS-enabled config
create_tls_config() {
    # Read existing config and add TLS settings
    cat > "${TLS_CONFIG_FILE}" <<EOF
# Loki configuration with TLS
# Generated by entrypoint-tls.sh

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_tls_config:
    cert_file: ${CERT_FILE}
    key_file: ${KEY_FILE}
  grpc_tls_config:
    cert_file: ${CERT_FILE}
    key_file: ${KEY_FILE}

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 24

analytics:
  reporting_enabled: false
EOF
    echo "TLS config created at ${TLS_CONFIG_FILE}"
}

# Main logic
if [ "${ENABLE_TLS}" = "true" ]; then
    echo "TLS mode enabled"

    # Validate required environment variables
    if [ -z "${STEPCA_URL}" ]; then
        echo "ERROR: STEPCA_URL is required when ENABLE_TLS=true"
        exit 1
    fi

    if [ -z "${STEPCA_FINGERPRINT}" ]; then
        echo "ERROR: STEPCA_FINGERPRINT is required when ENABLE_TLS=true"
        exit 1
    fi

    # Request certificate
    request_certificate

    # Create TLS config
    create_tls_config

    # Start Loki with TLS config
    echo "Starting Loki with TLS..."
    exec /usr/bin/loki -config.file="${TLS_CONFIG_FILE}" "$@"
else
    echo "TLS mode disabled, starting Loki normally..."
    exec /usr/bin/loki -config.file="${CONFIG_FILE}" "$@"
fi
