#!/bin/sh
# TLS-aware entrypoint for Prometheus
# Requests certificate from step-ca and configures TLS if enabled
# Also supports retention configuration via environment variables
set -e

TLS_DIR="/etc/prometheus/tls"
CERT_FILE="${TLS_DIR}/prometheus.crt"
KEY_FILE="${TLS_DIR}/prometheus.key"
CA_FILE="${TLS_DIR}/ca.crt"
WEB_CONFIG="/etc/prometheus/web-config.yml"

# Default retention settings (can be overridden via environment variables)
RETENTION_TIME="${RETENTION_TIME:-30d}"
RETENTION_SIZE="${RETENTION_SIZE:-}"

# Function to request certificate from step-ca
request_certificate() {
    echo "Requesting certificate from step-ca..."

    # Bootstrap trust to the CA
    step ca bootstrap --ca-url "${STEPCA_URL}" --fingerprint "${STEPCA_FINGERPRINT}" --force

    # Get hostname for certificate
    HOSTNAME=$(hostname)

    # Request certificate using ACME
    step ca certificate "${HOSTNAME}" "${CERT_FILE}" "${KEY_FILE}" \
        --ca-url "${STEPCA_URL}" \
        --provisioner acme \
        --not-after "${CERT_DURATION}" \
        --force

    # Copy root CA for client verification
    cp "$(step path)/certs/root_ca.crt" "${CA_FILE}"

    echo "Certificate obtained successfully"
}

# Function to create web config for TLS
create_web_config() {
    cat > "${WEB_CONFIG}" <<EOF
# TLS configuration for Prometheus
# Generated by entrypoint-tls.sh
tls_server_config:
  cert_file: ${CERT_FILE}
  key_file: ${KEY_FILE}
  # Optional: require client certificates
  # client_auth_type: RequireAndVerifyClientCert
  # client_ca_file: ${CA_FILE}
EOF
    echo "Web config created at ${WEB_CONFIG}"
}

# Build retention flags
build_retention_flags() {
    RETENTION_FLAGS=""

    if [ -n "${RETENTION_TIME}" ]; then
        RETENTION_FLAGS="${RETENTION_FLAGS} --storage.tsdb.retention.time=${RETENTION_TIME}"
        echo "Retention time: ${RETENTION_TIME}" >&2
    fi

    if [ -n "${RETENTION_SIZE}" ]; then
        RETENTION_FLAGS="${RETENTION_FLAGS} --storage.tsdb.retention.size=${RETENTION_SIZE}"
        echo "Retention size: ${RETENTION_SIZE}" >&2
    fi

    echo "${RETENTION_FLAGS}"
}

# Main logic
RETENTION_FLAGS=$(build_retention_flags)

if [ "${ENABLE_TLS}" = "true" ]; then
    echo "TLS mode enabled"

    # Validate required environment variables
    if [ -z "${STEPCA_URL}" ]; then
        echo "ERROR: STEPCA_URL is required when ENABLE_TLS=true"
        exit 1
    fi

    if [ -z "${STEPCA_FINGERPRINT}" ]; then
        echo "ERROR: STEPCA_FINGERPRINT is required when ENABLE_TLS=true"
        exit 1
    fi

    # Request certificate
    request_certificate

    # Create web config
    create_web_config

    # Start Prometheus with TLS
    echo "Starting Prometheus with TLS..."
    # shellcheck disable=SC2086
    exec /bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/prometheus \
        --web.console.libraries=/usr/share/prometheus/console_libraries \
        --web.console.templates=/usr/share/prometheus/consoles \
        --web.config.file="${WEB_CONFIG}" \
        ${RETENTION_FLAGS} \
        "$@"
else
    echo "TLS mode disabled, starting Prometheus normally..."
    # shellcheck disable=SC2086
    exec /bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/prometheus \
        --web.console.libraries=/usr/share/prometheus/console_libraries \
        --web.console.templates=/usr/share/prometheus/consoles \
        ${RETENTION_FLAGS} \
        "$@"
fi
