#!/bin/sh
# TLS-aware entrypoint for Prometheus
# Requests certificate from step-ca and configures TLS if enabled
# Also supports retention configuration via environment variables
set -eu

# =============================================================================
# Logging Functions
# =============================================================================
log_info()  { echo "INFO:  $*"; }
log_warn()  { echo "WARN:  $*" >&2; }
log_error() { echo "ERROR: $*" >&2; }

# =============================================================================
# Configuration
# =============================================================================
TLS_DIR="/etc/prometheus/tls"
CERT_FILE="${TLS_DIR}/prometheus.crt"
KEY_FILE="${TLS_DIR}/prometheus.key"
CA_FILE="${TLS_DIR}/ca.crt"
WEB_CONFIG="/etc/prometheus/web-config.yml"

# Default retention settings (can be overridden via environment variables)
RETENTION_TIME="${RETENTION_TIME:-30d}"
RETENTION_SIZE="${RETENTION_SIZE:-}"

# =============================================================================
# Functions
# =============================================================================

# Request certificate from step-ca
request_certificate() {
    log_info "Requesting certificate from step-ca..."

    # Bootstrap trust to the CA
    if ! step ca bootstrap --ca-url "${STEPCA_URL}" --fingerprint "${STEPCA_FINGERPRINT}" --force; then
        log_error "Failed to bootstrap CA trust"
        return 1
    fi

    # Get hostname for certificate
    HOSTNAME=$(hostname)
    log_info "Requesting certificate for hostname: ${HOSTNAME}"

    # Request certificate using ACME
    if ! step ca certificate "${HOSTNAME}" "${CERT_FILE}" "${KEY_FILE}" \
        --ca-url "${STEPCA_URL}" \
        --provisioner acme \
        --not-after "${CERT_DURATION:-24h}" \
        --force; then
        log_error "Failed to obtain certificate"
        return 1
    fi

    # Copy root CA for client verification
    if ! cp "$(step path)/certs/root_ca.crt" "${CA_FILE}"; then
        log_error "Failed to copy root CA certificate"
        return 1
    fi

    log_info "Certificate obtained successfully"
}

# Create web config for TLS
create_web_config() {
    log_info "Creating web config for TLS..."

    if ! cat > "${WEB_CONFIG}" <<EOF
# TLS configuration for Prometheus
# Generated by entrypoint-tls.sh
tls_server_config:
  cert_file: ${CERT_FILE}
  key_file: ${KEY_FILE}
  # Optional: require client certificates
  # client_auth_type: RequireAndVerifyClientCert
  # client_ca_file: ${CA_FILE}
EOF
    then
        log_error "Failed to create web config"
        return 1
    fi

    log_info "Web config created at ${WEB_CONFIG}"
}

# Build retention flags and log the settings
# Sets RETENTION_FLAGS global variable instead of using stdout to avoid mixing with logs
build_retention_flags() {
    RETENTION_FLAGS=""

    if [ -n "${RETENTION_TIME}" ]; then
        RETENTION_FLAGS="${RETENTION_FLAGS} --storage.tsdb.retention.time=${RETENTION_TIME}"
        log_info "Retention time: ${RETENTION_TIME}"
    fi

    if [ -n "${RETENTION_SIZE}" ]; then
        RETENTION_FLAGS="${RETENTION_FLAGS} --storage.tsdb.retention.size=${RETENTION_SIZE}"
        log_info "Retention size: ${RETENTION_SIZE}"
    fi
}

# Validate required TLS environment variables
validate_tls_config() {
    local valid=true

    if [ -z "${STEPCA_URL:-}" ]; then
        log_error "STEPCA_URL is required when ENABLE_TLS=true"
        valid=false
    fi

    if [ -z "${STEPCA_FINGERPRINT:-}" ]; then
        log_error "STEPCA_FINGERPRINT is required when ENABLE_TLS=true"
        valid=false
    fi

    if [ "${valid}" = "false" ]; then
        return 1
    fi
}

# =============================================================================
# Main
# =============================================================================
main() {
    build_retention_flags

    if [ "${ENABLE_TLS:-false}" = "true" ]; then
        log_info "TLS mode enabled"

        # Validate configuration
        if ! validate_tls_config; then
            log_error "TLS configuration validation failed"
            exit 1
        fi

        # Request certificate
        if ! request_certificate; then
            log_error "Certificate request failed"
            exit 1
        fi

        # Create web config
        if ! create_web_config; then
            log_error "Web config creation failed"
            exit 1
        fi

        # Start Prometheus with TLS
        log_info "Starting Prometheus with TLS..."
        # shellcheck disable=SC2086
        exec /bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/prometheus \
            --web.console.libraries=/usr/share/prometheus/console_libraries \
            --web.console.templates=/usr/share/prometheus/consoles \
            --web.config.file="${WEB_CONFIG}" \
            --web.enable-lifecycle \
            ${RETENTION_FLAGS} \
            "$@"
    else
        log_info "TLS mode disabled, starting Prometheus normally..."
        # shellcheck disable=SC2086
        exec /bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/prometheus \
            --web.console.libraries=/usr/share/prometheus/console_libraries \
            --web.console.templates=/usr/share/prometheus/consoles \
            --web.enable-lifecycle \
            ${RETENTION_FLAGS} \
            "$@"
    fi
}

main "$@"
